const reporter = require('cucumber-html-reporter');

const options = {
  theme: 'bootstrap', // Choose from bootstrap, hierarchy, foundation, etc.
  jsonFile: 'reports/cucumber_report.json', // Path to the JSON file generated by Cucumber.js
  output: 'reports/cucumber_report.html',   // Path to the HTML report
  reportSuiteAsScenarios: true,             // Display each feature as a suite
  scenarioTimestamp: true,                  // Add timestamps to scenarios
  launchReport: true,                       // Automatically open the report after generation
  metadata: {
    "App Version": "1.0.0",
    "Test Environment": "STAGING",
    "Browser": "Chrome",
    "Platform": "Ubuntu",
  }
};

reporter.generate(options);
