const reporter = require('cucumber-html-reporter');
const fs = require('fs');
const path = require('path');

// Define paths
const jsonFilePath = path.resolve('./reports/cucumber_report.json');
const htmlFilePath = path.resolve('./reports/cucumber_report.html');

if (!fs.existsSync(jsonFilePath)) {
  console.error(`Error: JSON file does not exist at ${jsonFilePath}`);
  process.exit(1);
}

const options = {
  theme: 'bootstrap', // Choose from bootstrap, hierarchy, foundation, etc.
  jsonFile: jsonFilePath, // Path to the JSON file generated by Cucumber.js
  output: htmlFilePath,   // Path to the HTML report
  reportSuiteAsScenarios: true,             // Display each feature as a suite
  scenarioTimestamp: true,                  // Add timestamps to scenarios
  launchReport: true,                       // Automatically open the report after generation
  metadata: {
    "App Version": "1.0.0",
    "Test Environment": "STAGING",
    "Browser": "Chrome",
    "Platform": "Ubuntu",
  }
};

reporter.generate(options);
