name: Cucumber Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Install dependencies for Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          curl \
          unzip \
          xz-utils \
          libx11-dev \
          libx11-xcb1 \
          libxcomposite1 \
          libxrandr2 \
          libgdk-pixbuf2.0-0 \
          libnss3 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libgbm1 \
          libasound2 \
          libxss1 \
          libappindicator3-1 \
          libsecret-1-0 \
          fonts-liberation \
          libappindicator3-1 \
          libnspr4
        # Install Google Chrome
        curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt --fix-broken install

    - name: Run tests
      run: |
        npm run test